### ISSUE TITLE
Uncaught Type Error after upgrading to 2.1.0

### ISSUE THREAD

**Issue by Nawu178** [dabeng/OrgChart#340]
I set up a chart on Friday and it worked perfectly. After updating to 2.1.0 today, I got the following error:

app.js:18913 Uncaught TypeError: $(...).orgchart is not a function

I instantiated exactly as before when it worked and did not change anything else.
var oc = $('#structure-target').orgchart(options);

I tried rolling back to 2.0.15 (the version I was running on Friday), but it was still giving me the same error.

**Comment by Nawu178** [comment]
I was able to get it working again by rolling back Jquery to 3.2.1 as well as OrgChart to 2.0.15

Would love to fix the issue though...

**Comment by Nawu178** [comment]
I'm now getting the same error again even when locking the version to 2.0.15. It appears that a jQuery folder is created in the node_modules sub folder (alongside the html2canvas folder). If I delete this jQuery folder, then everything works fine after compiling. If I update npm again, the jQuery folder is back and I get the error after compiling.

**Comment by rwpino** [comment]
@Nawu178  I m having the same issue and I don't how to fixed.. I working with orgChart inside a angular project.. few days back is was working well

**Comment by Nawu178** [comment]
@rwpino I did the same thing and it worked for a bit, but then for some reason the problem re-appeared even though I had the versions locked at 3.2.1 and 2.0.15.
I then figured out that if you deleted the jquery folder in node_modules/orgchart/node_modules/ then it worked after compiling. Problem is that npm install would re-download the jquery folder. I have now resolved to writing a custom script that would delete the jquery folder every time before I compile with npm. Its a duct tape fix but it works for now.

**Comment by Gericho91** [comment]
I find my problem in my case.
In JS file here:

if (typeof module === 'object' && typeof module.exports === 'object') {
    // factory(require('jquery'), window, document);
    factory(jQuery, window, document);
  } else {
    factory(jQuery, window, document);
  }

JQuery was added twice
